language: node_js

node_js:
  - '6'

env:
  global:
    - NODE_ENV=CI

cache:
  directories:
    - node_modules

script:
  - make link
  - make coverage

after_success:
  - "./node_modules/.bin/codecov"
